package com.spamshield.app

/**
 * On-device half of the text->features contract. The other half is ml_pipeline/text_features.py,
 * and the two MUST agree exactly: TextFeaturizerParityTest asserts this object reproduces golden
 * vectors generated by the Python side.
 *
 * Why this replaced the old tokenizer.json approach:
 *
 *  - The old code loaded a 20,823-word vocabulary and fed raw indices into a model whose
 *    embedding had only 10,000 rows. TFLite answered with "gather index out of bounds" on 21.5%
 *    of real messages. Here every id is `1 + hash % (NUM_BUCKETS - 1)`, so an out-of-range
 *    lookup is arithmetically impossible.
 *  - The old normalizer, `[^a-z0-9 ]`, deleted every Devanagari and Tamil character, so a Hindi
 *    scam SMS reached the model as an empty string. [normalize] keeps letters/digits of any script.
 *  - There is no vocabulary file to ship or keep in sync, which removes the drift that caused
 *    both bugs.
 *
 * Char n-grams are what make the classifier robust to the obfuscation spam relies on
 * ("l0ttery", "c1ick") and to Hinglish spelling variation ("kare"/"karo"/"karein").
 */
object TextFeaturizer {

    // --- Contract. Must match text_features.py exactly. ---
    const val NUM_BUCKETS = 20000
    const val MAX_FEATURES = 256
    private const val PAD_ID = 0
    private val CHAR_NGRAMS = intArrayOf(3, 4)
    private const val USE_WORD_BIGRAMS = true

    /**
     * Bumped whenever [normalize]/[tokenize] semantics change, even when NUM_BUCKETS/MAX_FEATURES
     * don't. NUM_BUCKETS/MAX_FEATURES only catch a SHAPE mismatch; this would catch a SEMANTIC
     * one - a model trained under different tokenization loaded with this code would not crash,
     * it would silently classify using different features than it was trained on. Currently 1
     * (unchanged) - see [maskDigits]' doc for why digit masking stayed out of this pipeline
     * despite being built and measured.
     */
    const val FEATURE_VERSION = 1

    const val MASK_TOKEN = "XXXX"
    private const val MIN_DIGIT_RUN_TO_MASK = 3
    // \p{Nd} (Unicode category "decimal digit number") matches non-ASCII digits too - Devanagari
    // ०-९, Arabic-Indic ٠-٩, etc - the same set Python's `\d` matches by default for str patterns.
    private val DIGIT_RUN = Regex("\\p{Nd}{$MIN_DIGIT_RUN_TO_MASK,}")

    /**
     * Replaces runs of [MIN_DIGIT_RUN_TO_MASK]+ consecutive digits with a fixed placeholder.
     * Mirrors `text_features.py:mask_digits` exactly.
     *
     * Used ONLY by [TelemetryClient] before a message's text is uploaded for retraining - NOT by
     * [normalize] below. That exclusion is deliberate and measured: masking digits before feature
     * extraction was tried, and two independent retrains both landed real-holdout F1 around
     * 0.85-0.88 (down from 0.9744), outside the model's own bootstrap confidence interval. The
     * false negatives it introduced mostly didn't even contain digits, meaning the harm was a
     * shift in what the whole embedding table learned to weight, not a loss of per-message signal.
     * So raw digits still reach the classifier unchanged; they just never reach the backend.
     */
    fun maskDigits(text: String): String = DIGIT_RUN.replace(text) { " $MASK_TOKEN " }

    private const val FNV_OFFSET = -0x7EE3623B // 0x811C9DC5 as a signed Int
    private const val FNV_PRIME = 0x01000193

    /**
     * 32-bit FNV-1a over UTF-8 bytes. Int overflow wraps two's-complement, which matches the
     * `& 0xFFFFFFFF` masking on the Python side; [toUInt] restores the unsigned value at the end.
     */
    fun fnv1a(text: String): UInt {
        var hash = FNV_OFFSET
        for (byte in text.toByteArray(Charsets.UTF_8)) {
            hash = hash xor (byte.toInt() and 0xFF)
            hash *= FNV_PRIME
        }
        return hash.toUInt()
    }

    /** Maps a token into [1, NUM_BUCKETS). 0 stays reserved for padding. */
    fun bucket(token: String): Int =
        1 + (fnv1a(token) % (NUM_BUCKETS - 1).toUInt()).toInt()

    /**
     * Keeps Unicode Letters, Marks and Numbers; everything else collapses to a single space.
     *
     * Marks are kept deliberately. Indic scripts write vowels as combining marks - the 'ा' in
     * 'आपका' is a combining spacing mark, not a letter - so a letters-and-digits-only rule
     * strips 'आपका' down to 'आपक' and discards most of the vowel information in Hindi, Tamil
     * and Bengali text. Java's getType() constants 1..11 are exactly categories L, M and N,
     * matching the Python side's `unicodedata.category(ch)[0] in ("L","M","N")`.
     *
     * Iterates by CODE POINT rather than by Char. Kotlin strings are UTF-16, so a non-BMP
     * character such as the "mathematical bold" letters spammers use to dodge filters
     * ("𝐖𝐈𝐍" = a styled WIN) occupies two Chars; walking Chars would split it and disagree
     * with Python, which iterates code points.
     */
    private fun isKept(codePoint: Int): Boolean {
        val type = Character.getType(codePoint)
        return type >= Character.UPPERCASE_LETTER.toInt() &&
                type <= Character.OTHER_NUMBER.toInt()
    }

    /**
     * Deliberately does NOT call [maskDigits] - see that function's doc for the measured accuracy
     * regression that caused this to be reverted. Raw digits still reach the classifier here.
     */
    fun normalize(text: String): String {
        val sb = StringBuilder(text.length)
        var prevSpace = true
        var i = 0
        while (i < text.length) {
            val cp = text.codePointAt(i)
            val charCount = Character.charCount(cp)
            val lowered = String(Character.toChars(cp)).lowercase()

            // A code point can lowercase into more than one char (rare, e.g. İ); mirror
            // Python by appending whatever the lowercase mapping produced.
            var keep = true
            var j = 0
            while (j < lowered.length) {
                val lcp = lowered.codePointAt(j)
                if (!isKept(lcp)) keep = false
                j += Character.charCount(lcp)
            }

            if (keep) {
                sb.append(lowered)
                prevSpace = false
            } else if (!prevSpace) {
                sb.append(' ')
                prevSpace = true
            }
            i += charCount
        }
        return sb.toString().trim()
    }

    fun tokenize(text: String): List<String> =
        normalize(text).split(" ").filter { it.isNotEmpty() }

    /** Ordered hashed feature ids: word unigrams, then bigrams, then char n-grams. */
    fun extractFeatures(text: String): List<Int> {
        val words = tokenize(text)
        if (words.isEmpty()) return emptyList()

        val feats = ArrayList<Int>(MAX_FEATURES)
        for (w in words) feats.add(bucket(w))

        if (USE_WORD_BIGRAMS) {
            for (i in 0 until words.size - 1) feats.add(bucket(words[i] + " " + words[i + 1]))
        }

        for (w in words) {
            // '<' and '>' cannot appear in normalized text, so they are safe boundary markers.
            val padded = "<$w>"
            val cps = padded.codePoints().toArray()
            for (n in CHAR_NGRAMS) {
                if (cps.size >= n) {
                    for (i in 0..cps.size - n) {
                        feats.add(bucket(String(cps, i, n)))
                    }
                }
            }
        }
        return feats
    }

    /** Fixed-length, zero-padded vector ready for the TFLite interpreter. */
    fun featurize(text: String): IntArray {
        val feats = extractFeatures(text)
        val out = IntArray(MAX_FEATURES) { PAD_ID }
        val n = minOf(feats.size, MAX_FEATURES)
        for (i in 0 until n) out[i] = feats[i]
        return out
    }
}
